### ISSUE TITLE
Intersection cannot be accessed

### ISSUE THREAD

**Issue by xivk** [anyways-open/cycling-frontend#60]
https://routeplanner.bike.brussels/#15.76/50.8181/4.3772?sb=true&o=4.3751175,50.8198880&d=4.3743753,50.8203894&p=profile1

![image](https://user-images.githubusercontent.com/1128068/85427610-e3723280-b573-11ea-8c18-6714f9a291f0.png)

**Comment by pietervdvn** [comment]
https://www.openstreetmap.org/way/40151775 has a 'cyclway:right=no', which is currently still interpreted wrongly.

https://github.com/anyways-open/routing-profiles/pull/35 should fix this

**Comment by xivk** [comment]
Already better, still an issue there:

![image](https://user-images.githubusercontent.com/1128068/85532633-c2f3b800-b607-11ea-9039-e5669855f064.png)

**Comment by pietervdvn** [comment]
The routing follows the expected behaviour, it's just that the colours aren't added.

I've fixed that here: https://www.openstreetmap.org/changeset/87077971

**Comment by pietervdvn** [comment]
![image](https://user-images.githubusercontent.com/1466478/85710597-b5f9c600-b6e6-11ea-9e46-6579101807fe.png)
